# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: go benchmark

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  tests:
    runs-on: ubuntu-latest
    container: golang:1.25-alpine
    name: Run benchmark
    steps:
      - uses: actions/checkout@v6
        name: Checkout
        id: checkout
        with:
          sparse-checkout: |
            .github
            .gitignore
            .golangci.yml
            README.md
            LICENSE
      - name: Download and install dependencies
        id: install-deps
        run: |
          go mod download
          go mod tidy
          go mod vendor
      - name: Run go benchmark
        id: go-benchmark
        run: |
            go test github.com/euphoria-laxis/argon2 -bench=. -benchtime=10x -benchmeum