name: test

on:
    push:
        tags:
            - v*
    pull_request:
        branches:
            - master
            - release/*
            - dev/*

jobs:
    test:
        runs-on: ubuntu-latest
        container: golang:1.25-alpine
        name: Test package
        steps:
            - uses: actions/checkout@v6
              name: Checkout
              id: checkout
              with:
                  sparse-checkout: |
                      .github
                      .gitignore
                      .golangci.yml
                      README.md
                      LICENSE
            - name: Download and install dependencies
              id: install-deps
              run: |
                  go mod download
                  go mod tidy
                  go mod vendor
            - name: Run go tests
              id: go-test
              run: |
                  go test -v github.com/euphoria-laxis/argon2/hashing